FROM debian:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y lsb-release apt-utils software-properties-common
RUN add-apt-repository \
   "deb [arch=amd64] http://deb.debian.org/debian \
   $(lsb_release -cs) \
   universe"
RUN apt-get update && apt-get install -y php-cli cron
RUN touch /var/log/cron.log
CMD /usr/bin/php ${MOODLE_DOCKER_WWWROOT}/admin/cli/cron.php && tail -f /var/log/cron.log
