FROM debian:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y lsb-release apt-utils software-properties-common
RUN add-apt-repository \
   "deb [arch=amd64] http://deb.debian.org/debian \
   $(lsb_release -cs) \
   universe"
RUN apt-get update && apt-get install -y php-cli php-pgsql cron
RUN echo "*/1 * * * * /usr/bin/php /var/www/html/admin/cli/cron.php > /dev/null" | crontab -
CMD cron -f

